[book]
authors = ["王兴彬_Binboy"]
language = "zh-CN"
multilingual = false
src = "src"
title = "棒棒彬的第二大脑"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
google-analytics = "UA-160717450-2"
git-repository-url = "https://github.com/Binlogo/Knowledge-Track"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Binlogo/Knowledge-Track/edit/main/{path}"

[output.html.fold]
enable = false
level = 0

[output.html.search]
limit-results = 15
